matrix:
  include:
    - language: scala
      scala:
        - 2.9.3
        - 2.11.11

    - language: ruby
      rvm:
        - 2.5
        - 2.6
        - jruby
        - truffleruby

    - language: go
      go:
        - 1.x
        - master 

