matrix:
  include:
    - language: scala
      scala:
        - stable
      before_install:
        - cd code/Scala
      after_success:
        - echo "Test Success"

    - language: ruby
      rvm:
        - 2.6
        - jruby
        - truffleruby

    - language: go
      go:
        - 1.14
        - master  
